language: node_js
node_js:
  - 12
branchs:
  only:
  - main
addons:
  apt:
    packages:
    - sshpass
install:
  "npm install"
script:
  - "npm run build"
# after_success:
#   - ./script/deploy.sh


